[test]
coverageSkipTestFiles = true  # default false
preload = ["./test-preload.ts"]
coveragePathIgnorePatterns = [
    "packages/core/src/interfaces/**",
    "packages/integration/src/interfaces/**",
    "packages/core/dist/**",
    "packages/integration/dist/**"
]